### PR TITLE
Prepare the module for the next release cycle

### PR DESCRIPTION
**Pull request by moshonk**
Hi @ckemar,

We need to prepare this module for the next release cycle.

cc @ningosi

### CODE REVIEW

**Comment by ningosi** [comment]
@moshonk when doing a release, the maven plug in should take care of this. Has a release been done recently?

**Comment by ningosi** [comment]
@moshonk what if you have one PR having several commits instead of having those many PRs with individual ones have short content? for now We will never know what to merge first in what order, especially if they are built on top of each other

**Comment by moshonk** [comment]
@ningosi, the code changes that I am suggesting will have to go into a minor version (1.1 perhaps). And I believe what the maven plugin will do is to drop the "-SNAPSHOT" string appended to the version number; correct me if am wrong.

About the several pull requests, each pull request relates to an indicator that I reviewed and made code corrections to. I thought it would be easier to review each change independently rather than clutter all the changes in a single pull request. The sequence of merging the pull requests doesn't really matter since the changes I made affect the indicators individually.

**Comment by ningosi** [comment]
@moshonk Yes, with the maven release life cycle, the plug will replace the snap shot with the number specified for the release and prepare the code for next iteration

**Pull request merged**
